# Generated by Django 5.1.4 on 2025-01-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularreview',
            name='parent',
        ),
    ]
