# Generated by Django 5.1.4 on 2025-01-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_remove_popularreview_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPlacesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_places_category', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='popularplaces',
            name='popular_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_name', to='country.popularplacescategory'),
        ),
        migrations.AlterField(
            model_name='popularplaces',
            name='popular_name_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_name', to='country.popularplacescategory'),
        ),
        migrations.AlterField(
            model_name='popularplaces',
            name='popular_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_name', to='country.popularplacescategory'),
        ),
        migrations.AlterField(
            model_name='popularplaces',
            name='popular_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_name', to='country.popularplacescategory'),
        ),
    ]
