# Generated by Django 5.1.4 on 2025-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_popularplacescategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularplaces',
            name='popular_name_en',
        ),
        migrations.RemoveField(
            model_name='popularplaces',
            name='popular_name_ar',
        ),
        migrations.RemoveField(
            model_name='popularplaces',
            name='popular_name_ru',
        ),
        migrations.AlterField(
            model_name='popularplaces',
            name='popular_name',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='PopularPlacesCategory',
        ),
    ]
