# Generated by Django 5.1.4 on 2025-01-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_remove_popularplaces_popular_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractionreview',
            old_name='comment',
            new_name='attraction_comment',
        ),
        migrations.AlterUniqueTogether(
            name='attractionreview',
            unique_together=set(),
        ),
    ]
