# Generated by Django 5.1.4 on 2025-01-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_rename_comment_attractionreview_attraction_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery_review_image/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_review_image', to='country.galleryreview')),
            ],
        ),
    ]
