# Generated by Django 5.1.4 on 2025-01-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_galleryreviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='hotels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hotel', to='country.hotels'),
            preserve_default=False,
        ),
    ]
