# Generated by Django 5.1.4 on 2025-01-08 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_favoriteitem_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='country_favorite',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
