# Generated by Django 5.1.4 on 2025-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_remove_favorite_country_favorite_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
