# Generated by Django 5.1.4 on 2025-01-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_remove_kitchenreview_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenreview',
            name='service_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
