# Generated by Django 5.1.4 on 2025-01-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_popularplaces_popular_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='specialized_menu_ru',
            field=models.TextField(null=True),
        ),
    ]
