# Generated by Django 5.1.4 on 2025-01-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_kitchen_specialized_menu_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenlocation',
            name='address_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenlocation',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kitchenlocation',
            name='address_ru',
            field=models.TextField(null=True),
        ),
    ]
