# Generated by Django 5.1.4 on 2025-01-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_kitchenlocation_address_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='bikes_ar',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='bikes_en',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='bikes_ru',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cars_ar',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cars_en',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='cars_ru',
        ),
    ]
