# Generated by Django 5.1.4 on 2025-01-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_kitchenreview_service_rating'),
        ('country', '0012_remove_hotels_bikes_ar_remove_hotels_bikes_en_and_more'),
    ]

    operations = [
    ]
