# Generated by Django 5.1.4 on 2025-01-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_merge_20250120_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularplaces',
            name='popular_name_ar',
        ),
        migrations.RemoveField(
            model_name='popularplaces',
            name='popular_name_en',
        ),
        migrations.RemoveField(
            model_name='popularplaces',
            name='popular_name_ru',
        ),
    ]
