# Generated by Django 5.1.4 on 2025-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_remove_popularplaces_popular_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='popular_name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
