# Generated by Django 5.1.4 on 2025-01-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0015_popularplaces_popular_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='totry',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='totry',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='totry',
            name='description_ru',
        ),
    ]
