# Generated by Django 5.1.4 on 2025-01-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0016_remove_totry_description_remove_totry_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='region',
        ),
        migrations.AddField(
            model_name='attractions',
            name='popular_places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_places', to='country.popularplaces'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='region_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.region_categoty'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='popular_places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.popularplaces'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_region', to='country.region_categoty'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.region_categoty'),
        ),
    ]
