# Generated by Django 5.1.4 on 2025-01-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_remove_attractions_region_attractions_popular_places_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_description',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_description_ar',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_description_en',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_description_ru',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currency_image',
        ),
        migrations.CreateModel(
            name='Currency_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_description', to='country.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Currency_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='front_image_currency')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='back_image_currency')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_image', to='country.currency')),
            ],
        ),
    ]
