# Generated by Django 5.1.4 on 2025-02-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0018_remove_currency_currency_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('title', models.CharField(max_length=52)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert', to='country.eventcategories')),
            ],
        ),
    ]
