# Generated by Django 5.1.4 on 2025-02-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0019_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='kitchenlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Долгота'),
        ),
    ]
