# Generated by Django 5.1.4 on 2025-02-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0020_kitchenlocation_latitude_kitchenlocation_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='kitchenlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота'),
        ),
    ]
