# Generated by Django 5.1.4 on 2025-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0023_postattraction_postgallery_posthotel_postkitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='popularplaces',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота'),
        ),
    ]
