# Generated by Django 5.1.4 on 2025-03-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0024_hotels_latitude_hotels_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='type_attraction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
