# Generated by Django 5.1.4 on 2025-03-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0025_attractions_type_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='type_attraction_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='type_attraction_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attractions',
            name='type_attraction_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
