# Generated by Django 5.1.4 on 2025-03-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0026_attractions_type_attraction_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractionreview',
            old_name='client_home',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='attractionreview',
            old_name='attraction_comment',
            new_name='comment',
        ),
        migrations.CreateModel(
            name='ReplyToAttractionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_reviews', to='country.attractionreview')),
            ],
        ),
        migrations.DeleteModel(
            name='RegionReview',
        ),
    ]
