# Generated by Django 5.1.4 on 2025-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0027_rename_client_home_attractionreview_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionreview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Рейтинг'),
        ),
    ]
