# Generated by Django 5.1.4 on 2025-03-07 11:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0029_remove_hotels_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturekitchenmain',
            name='description_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='culturekitchenmain',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='culturekitchenmain',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='culturekitchenmain',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturekitchenmain',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturekitchenmain',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
