# Generated by Django 5.1.4 on 2025-03-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0030_culturekitchenmain_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyandhygiene',
            name='icon',
        ),
    ]
