# Generated by Django 5.1.4 on 2025-03-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0031_remove_safetyandhygiene_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytoattractionreview',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replytoattractionreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_attraction_reviews', to='country.attractionreview'),
        ),
    ]
