# Generated by Django 5.1.4 on 2025-03-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0033_replytoattractionreview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelsreview',
            old_name='client_hotel',
            new_name='client',
        ),
    ]
