# Generated by Django 5.1.4 on 2025-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0034_rename_client_hotel_hotelsreview_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenreview',
            old_name='client_kitchen',
            new_name='client',
        ),
    ]
