# Generated by Django 5.1.4 on 2025-03-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0035_rename_client_kitchen_kitchenreview_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryreview',
            old_name='client_gallery',
            new_name='client',
        ),
    ]
