# Generated by Django 5.1.4 on 2025-03-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0040_replytogalleryreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattraction',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='postattraction',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
