# Generated by Django 5.1.4 on 2025-03-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0041_remove_postattraction_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpopular',
            old_name='post_popular',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postpopular',
            old_name='user_popular',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postpopular',
            unique_together={('user', 'post')},
        ),
    ]
