# Generated by Django 5.1.4 on 2025-03-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0042_rename_post_popular_postpopular_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posthotel',
            old_name='post_hotel',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posthotel',
            old_name='user_hotel',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='posthotel',
            unique_together={('user', 'post')},
        ),
    ]
