# Generated by Django 5.1.4 on 2025-03-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0043_rename_post_hotel_posthotel_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postkitchen',
            old_name='post_kitchen',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postkitchen',
            old_name='user_kitchen',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postkitchen',
            unique_together={('user', 'post')},
        ),
    ]
