# Generated by Django 5.1.4 on 2025-03-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0044_rename_post_kitchen_postkitchen_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgallery',
            old_name='post_gallery',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postgallery',
            old_name='user_gallery',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='postgallery',
            unique_together={('user', 'post')},
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='posthotel',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='postkitchen',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='postpopular',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
