# Generated by Django 5.1.4 on 2025-03-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0045_rename_post_gallery_postgallery_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.kitchen'),
        ),
    ]
