# Generated by Django 5.1.4 on 2025-03-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0046_favoriteitem_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventcategories',
            name='category',
            field=models.CharField(blank=True, choices=[('Concert', 'Concert'), ('Cinema', 'Cinema'), ('Leisure', 'Leisure'), ('Exhibitions', 'Exhibitions'), ('Theater', 'Theater'), ('Master classes', 'Master classes'), ('Tourism', 'Tourism')], max_length=20, null=True),
        ),
    ]
