# Generated by Django 5.1.4 on 2025-03-09 09:26

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0047_event_ticket_alter_eventcategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='popular_places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='country.popularplaces'),
        ),
    ]
