# Generated by Django 5.1.4 on 2025-03-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0048_event_popular_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.culturecategory'),
        ),
        migrations.AlterField(
            model_name='culturecategory',
            name='culture_name',
            field=models.CharField(choices=[('Games', 'Games'), ('National clothes', 'National clothes'), ('Hand crafts', 'Hand crafts'), ('Currency', 'Currency'), ('National instruments', 'National instruments'), ('Kitchen', 'Kitchen')], max_length=35),
        ),
    ]
