# Generated by Django 5.1.4 on 2025-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0049_culture_culture_alter_culturecategory_culture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplaces',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
