# Generated by Django 5.1.4 on 2025-03-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0050_popularplaces_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularreview',
            old_name='popular',
            new_name='popular_place',
        ),
    ]
