# Generated by Django 5.1.4 on 2025-03-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0051_rename_popular_popularreview_popular_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenreview',
            old_name='kitchen_region',
            new_name='kitchen',
        ),
    ]
