# Generated by Django 5.1.4 on 2025-03-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0053_rename_created_date_hotelsreview_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractionreview',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
