# Generated by Django 5.1.4 on 2025-03-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0055_rename_created_at_attractionreview_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='attractions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.attractions'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.gallery'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='hotels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hotel', to='country.hotels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.kitchen'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favorite',
            name='popular_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.popularplaces'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'attractions', 'popular_region', 'gallery', 'kitchen', 'hotels')},
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
    ]
