# Generated by Django 5.1.4 on 2025-03-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0056_favorite_attractions_favorite_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_ar', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('website', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='popular_region',
            new_name='popular_place',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'attractions', 'popular_place', 'kitchen', 'hotels')},
        ),
        migrations.CreateModel(
            name='AirLineDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.CharField(max_length=250)),
                ('directions_en', models.CharField(max_length=250, null=True)),
                ('directions_ru', models.CharField(max_length=250, null=True)),
                ('directions_ar', models.CharField(max_length=250, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_tickets', to='country.airlinetickets')),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='gallery',
        ),
    ]
