# Generated by Django 5.1.4 on 2025-03-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0057_airlinetickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='hotels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country.hotels'),
        ),
    ]
