# Generated by Django 5.1.4 on 2025-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0058_alter_favorite_hotels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('attractions__isnull', False)), fields=('user', 'attractions'), name='unique_user_attraction'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('popular_place__isnull', False)), fields=('user', 'popular_place'), name='unique_user_popular_place'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('kitchen__isnull', False)), fields=('user', 'kitchen'), name='unique_user_kitchen'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('hotels__isnull', False)), fields=('user', 'hotels'), name='unique_user_hotels'),
        ),
    ]
