# Generated by Django 5.1.4 on 2025-03-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0059_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_attraction',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_popular_place',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_kitchen',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_hotels',
        ),
    ]
